// Generated by Dagger (https://dagger.dev).
package com.technolink.qmeter.presentation.auth;

import com.technolink.qmeter.di.factory.ViewModelProviderFactory;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import dagger.android.support.DaggerAppCompatActivity_MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AuthenticateActivity_MembersInjector implements MembersInjector<AuthenticateActivity> {
  private final Provider<DispatchingAndroidInjector<Object>> androidInjectorProvider;

  private final Provider<ViewModelProviderFactory> factoryProvider;

  public AuthenticateActivity_MembersInjector(
      Provider<DispatchingAndroidInjector<Object>> androidInjectorProvider,
      Provider<ViewModelProviderFactory> factoryProvider) {
    this.androidInjectorProvider = androidInjectorProvider;
    this.factoryProvider = factoryProvider;
  }

  public static MembersInjector<AuthenticateActivity> create(
      Provider<DispatchingAndroidInjector<Object>> androidInjectorProvider,
      Provider<ViewModelProviderFactory> factoryProvider) {
    return new AuthenticateActivity_MembersInjector(androidInjectorProvider, factoryProvider);
  }

  @Override
  public void injectMembers(AuthenticateActivity instance) {
    DaggerAppCompatActivity_MembersInjector.injectAndroidInjector(instance, androidInjectorProvider.get());
    injectFactory(instance, factoryProvider.get());
  }

  @InjectedFieldSignature("com.technolink.paydaychallenge.presentation.auth.AuthenticateActivity.factory")
  public static void injectFactory(AuthenticateActivity instance,
      ViewModelProviderFactory factory) {
    instance.factory = factory;
  }
}
